TZ: Asia/Shanghai
JD_COOKIE: pt_key=AAJh8Q37ADCLlt_8pNHvcwyRjBKw3KIVIS7_M97GPgy90Xta5fEQC980dcPw9CCobKLDQfcTOtA;pt_pin=jd_40e75548688f1;&pt_key=AAJh3VCPADB4ylbKiEq2V10hvMQgytLedeIJz-iyGPfCQVt8mdpajb4K0um7SbJZqFKKJ_eFJ4U;pt_pin=jd_NsBrJgWSinIN;&pt_key=AAJh86Q9ADBAPpV9F48IPZ7sMaaoUCkwMgqBdn4kk6IezI44pt9MnUv25GSrzbqKcs-Yx_Xl-ao;pt_pin=jd_750c168953f40;&pt_key=AAJh8WtxADBSY8jHqT3WyBf2eWoiGifxiQpLWSeWfh7QWw-FQrUZRf7vKCvwKRZfADp0rSFYWeE;pt_pin=jd_487aa74a44f91;&pt_key=AAJh7tETADAEMFrYM4rNADF_ET1b-rSogQQf0bCDQghfmcuTH3eboM8tCJENVzUNVyLhSKpZ-Go;pt_pin=jd_6f5ef640cfbfa;&pt_key=AAJh7P3IADBbGdO4x7gRNfSmb-bwNC8n_GF-_zbmc89naa29T0ipclNoHbxUPip8EP0e2w1EtvE;pt_pin=%E9%BB%84%E5%B0%8F%E5%85%AD1128;&pt_key=AAJh86FYADCzRDzil3_9M13JlBtB02BgSSoQtce_lVJOGeQ2wD73fWoeQnytU9_jz0Ulf5Pttr0;pt_pin=jd_5d85084d4f311;&pt_key=AAJh6_FRADB1DcvJ296RbJaMBSYkemK6I_zQDqzlo9sJg8tHRIjIxVmPQg3HLEA2tdmDe2k988c;pt_pin=jd_WhMTrnCrCscO;
JD_TRY: 'true'
TG_BOT_TOKEN: 2090671085:AAHbzxY6rynhYFMbOCdP0SXnYGmgjQ9iUgo
TG_USER_ID: 1934878222
PUSH_KEY: SCT75613T9wYKTMpMe2hW8pdh1sC4W0eF
PLANT_BEAN_SHARECODES: e7lhibzb3zek3ke2ubzftt4nrp75ebluv7nlfqq
DDFACTORY_SHARECODES: T0225KkcRB5M8lHSJBLynP9cdQCjVWnYaS5kRrbA
DREAM_FACTORY_SHARE_CODES: fYmERa-vHUWNYGMfUYvoYg==
JDSGMH_SHARECODES: T0225KkcRB5M8lHSJBLynP9cdQCjVQmoaT5kRrbA
JOY_RUN_HELP_MYSELF: 'true'
FRUIT_BEAN_CARD: 'true'
FRUITSHARECODES: fd1c81b5254143c6b7d69df874381d37
PETSHARECODES: MTEyNzEzMjc0MDAwMDAwMDU1MjE5Mzgx
MARKET_COIN_TO_BEANS: 20
JOY_FEED_COUNT: 80
MONEY_TREE_SELL_FRUIT: 'true'
JDJOY_HELPSELF: 'true'
JDJOY_APPLYJDBEAN: 2000

